#
# sonarqube cluster in kubernetes 
#
# sonarqube configuration
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-configmap
  labels:
    app: sonarqube
data: 
  SONARQUBE_JDBC_USERNAME: "sonarUser"
  SONARQUBE_JDBC_PASSWORD: "123456"
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres-sonar-0.postgres-sonar-h:5432/sonarDB"
---
#
# sonarqube headless service
#
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-h
  labels:
    app: sonarqube
spec:
  type: NodePort
  ports:
    - name: sonarqube
      port: 9000
      targetPort: 9000
      nodePort: 30003
      protocol: TCP
  selector:
    app: sonarqube

---


#
# sonarqube containers
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  serviceName: sonarqube-h
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
        envFrom: 
        - configMapRef:
            name: sonarqube-configmap
        livenessProbe:
          httpGet:
            path: /sessions/new
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /sessions/new
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 6
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
        volumeMounts:
        - mountPath: /opt/sonarqube/conf
          name: sonarqube-data
          subPath: conf
        - mountPath: /opt/sonarqube/data
          name: sonarqube-data
          subPath: data
        - mountPath: /opt/sonarqube/extensions
          name: sonarqube-data
          subPath: extensions
  volumeClaimTemplates: 
  - metadata: 
      name: sonarqube-data
    spec: 
      accessModes: ["ReadWriteMany"]
      resources:
        requests: 
          storage: 2Gi
